import { VehicleWithOwner } from './VehicleList';

export const mockVehicles: VehicleWithOwner[] = [
  {
    id: '1',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    registrationNumber: 'TS-001',
    nickname: 'City Runner',
    batteryCapacity: 75,
    connectorTypes: ['CCS2'],
    status: 'active',
    ownerId: 'owner-1',
    ownerName: 'John Doe',
    ownerEmail: 'john@example.com',
  },
  {
    id: '2',
    make: 'Nissan',
    model: 'Leaf',
    year: 2022,
    registrationNumber: 'NI-002',
    nickname: 'Green Machine',
    batteryCapacity: 62,
    connectorTypes: ['CHAdeMO', 'CCS2'],
    status: 'active',
    ownerId: 'owner-2',
    ownerName: 'Jane Smith',
    ownerEmail: 'jane@example.com',
  },
  {
    id: '3',
    make: 'BMW',
    model: 'i4',
    year: 2023,
    registrationNumber: 'BM-003',
    nickname: 'Premium Ride',
    batteryCapacity: 81,
    connectorTypes: ['CCS2'],
    status: 'active',
    ownerId: 'owner-3',
    ownerName: 'Robert Johnson',
    ownerEmail: 'robert@example.com',
  },
  {
    id: '4',
    make: 'Audi',
    model: 'e-tron',
    year: 2023,
    registrationNumber: 'AU-004',
    nickname: 'Electric Luxury',
    batteryCapacity: 95,
    connectorTypes: ['CCS2'],
    status: 'active',
    ownerId: 'owner-4',
    ownerName: 'Sarah Williams',
    ownerEmail: 'sarah@example.com',
  },
  {
    id: '5',
    make: 'Chevrolet',
    model: 'Bolt EV',
    year: 2022,
    registrationNumber: 'CH-005',
    nickname: 'Budget Friendly',
    batteryCapacity: 65,
    connectorTypes: ['CCS2'],
    status: 'inactive',
    ownerId: 'owner-5',
    ownerName: 'Michael Brown',
    ownerEmail: 'michael@example.com',
  },
  {
    id: '6',
    make: 'Volkswagen',
    model: 'ID.4',
    year: 2023,
    registrationNumber: 'VW-006',
    nickname: 'Family SUV',
    batteryCapacity: 77,
    connectorTypes: ['CCS2'],
    status: 'active',
    ownerId: 'owner-6',
    ownerName: 'Emma Davis',
    ownerEmail: 'emma@example.com',
  },
  {
    id: '7',
    make: 'Hyundai',
    model: 'Ioniq 5',
    year: 2023,
    registrationNumber: 'HY-007',
    nickname: 'Fast Charger',
    batteryCapacity: 84,
    connectorTypes: ['CCS2'],
    status: 'active',
    ownerId: 'owner-7',
    ownerName: 'David Wilson',
    ownerEmail: 'david@example.com',
  },
  {
    id: '8',
    make: 'Kia',
    model: 'EV6',
    year: 2023,
    registrationNumber: 'KI-008',
    nickname: 'Stylish EV',
    batteryCapacity: 77,
    connectorTypes: ['CCS2'],
    status: 'active',
    ownerId: 'owner-8',
    ownerName: 'Lisa Anderson',
    ownerEmail: 'lisa@example.com',
  },
];
